steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'beta'
  - 'functions'
  - 'deploy'
  - '$_FUNCTION_NAME'
  #- '--stage-bucket=$_BUCKET_NAME'
  - '--entry-point=main'
  - '--trigger-http'

substitutions:
  _FUNCTION_NAME: banek
  #_BUCKET_NAME: philmod-tmp
